name: ci-test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_DB: simple_bank
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: secret
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5434:5432
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21.5"
            - name: Install golang-migrate
              run: |
                  curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
                  sudo mv migrate /usr/bin
                  which migrate
            - name: Run migrations
              run: make migrateup
              env:
                  DB_DRIVER: postgres
                  DB_SOURCE: postgresql://root:${{secrets.DB_PASSWORD}}@localhost:5434/simple_bank?sslmode=disable
            - name: Test
              run: make test
              env:
                  DB_DRIVER: postgres
                  DB_SOURCE: postgresql://root:${{secrets.DB_PASSWORD}}@localhost:5434/simple_bank?sslmode=disable
                  SERVER_ADDRESS: 0.0.0.0:8080
